package io.finix.payments.enums;

public enum BusinessType {

  INDIVIDUAL_SOLE_PROPRIETORSHIP,
  CORPORATION,
  LIMITED_LIABILITY_COMPANY,
  PARTNERSHIP,
  LIMITED_PARTNERSHIP,
  GENERAL_PARTNERSHIP,
  ASSOCIATION_ESTATE_TRUST,
  TAX_EXEMPT_ORGANIZATION,
  INTERNATIONAL_ORGANIZATION,
  GOVERNMENT_AGENCY,
  JOINT_VENTURE

}
